// Dependencies
import Head from 'next/head'

// Misc
import { Inter } from '@next/font/google'
import Image from 'next/image'

// Pages
import { MultiStepLayout } from '../layouts'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Multi Step Form Main</title>
        <meta name="description" content="Generated by Multi Step Form Main" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
